### ISSUE TITLE
The first CLI program is a little complex.

### ISSUE THREAD

**Issue by mfrw** [RN0311/WWG-Go-Tutorial-Delhi#2]
IMHO, the first CLI program is a little complex and _may_ intimidate a newcomer.
I think to start with something as simple as fibonacci, should set the pace, where
it would be quite easy to show all the `go run/build` stuff.

**Comment by RN0311** [comment]
Perfecto!
Will update it soon!

Thanks, @mfrw for marvelous insights :wink:
